help:
	@echo ""
	@echo "Makefile to build Docker container images, tag them and push them to a registry. The following targets can be used:"
	@echo ""
	@echo "  help:  Show this help and is the default goal"
	@echo "  all:   Run tasks to buildi the container image, tag it, save it as OCI file to disk and push it to a registry."
	@echo "  build: Just build the container image and tag it with the projects folder name"
	@echo "  tag:   Tag an existing image with a registry, organisation name and project name"
	@echo "  oci:   Create an OCI image file in images/image.oci"
	@echo "  push:  Push a tagged image to a registry, default tag: $(DOCKER_TAG)"
	@echo "  prune: Clean all that is actively used"
	@echo ""
	@echo "Arguments to modify the build:"
	@echo ""
	@echo "  BASE_IMAGE:         The base image to build this container image, default: $(BASE_IMAGE)"
	@echo "  BASE_IMAGE_VERSION: The version of the base image to build this project, default: $(BASE_IMAGE_VERSION)"
	@echo "  DOCKER_BUILD_FLAGS: Flags for the docker build command, .e.g. DOCKER_BUILD_FLAGS=--no-cache to force rebuild."
	@echo "  DOCKER_REGISTRY:    Registry to push the image to, default is set to docker.io"
	@echo "  DOCKER_ORG:         Organisation where the image should pushed in the registry, default is set to opennms."
	@echo "  DOCKER_PROJECT:     Name of the project in the registry, the default is set to the folder name."
	@echo ""
	@echo "Example:"
	@echo ""
	@echo "  make tag DOCKER_REGISTRY=myregistry.com DOCKER_ORG=myorg DOCKER_BUILD_FLAGS=--no-cache"
	@echo ""

.DEFAULT_GOAL := help
